[package]
name = "black-forest-survivor"
version = "0.1.0"
edition = "2024"

[dependencies]
glox = "0.1.5"
ggsdk = "0.1.10"
glow = "0.16.0"
glam = "0.30.9"
slotmap = "1.1.1"
endlessgrid = "0.2.3"
shufflebag = "0.1.1"
rand = "0.9.2"